### ISSUE TITLE
tons of web requests fetching all players

### ISSUE THREAD

**Issue by AC6y86** [ThomasMorgani/AmericanSportScraper#5]
When doing "players all", it's spinning up a bunch of instances of chrome.  About 20 teams in, the system grinds to a halt.  My workaround was to pass in null for the playerDataRoster function.  Couldn't figure out how to issue the equivalent of a Stop in pupeteer.

**Comment by ThomasMorgani** [comment]
this was actually opening each team page in a new tab. Added a check to see if browsers has tabs open, if so use tab 0 to navigate to team page.

this should be fixed 1282722b1044efe91e3109d2305ddbb66b7a4514

**Comment by ThomasMorgani** [comment]
1282722
