### ISSUE TITLE
Cardinals and Ravens rosters not parsed

### ISSUE THREAD

**Issue by AC6y86** [ThomasMorgani/AmericanSportScraper#6]
These are the first 2 teams on the rosters page, havn't yet debugged why the team urls are not getting scraped.

**Comment by ThomasMorgani** [comment]
it  appears the selector we are querying is not consistent ([aria-label="View Profile"])
For some reason the team name will be added randomly to the text. for arizona's case it appears as "View Arizona Cardinals Profile"

will rewrite selector

**Comment by ThomasMorgani** [comment]
this seems to be reliable enough
ea3e544a99536cee16b1a37fe39c86d2e6adce74
